### ISSUE TITLE
Link to "download the eagle library" in the readme.md is broken

### ISSUE THREAD

**Issue by AHurnell** [spark/hardware-libraries#8]
I think the target url should be 

https://github.com/particle-iot/hardware-libraries/raw/master/Eagle/Particle-Devices.zip

rather than

https://github.com/particle-iot/hardware-libraries/raw/master/Eagle/Particle-Devices.lbr.zip

but I'm not certain.

**Comment by rickkas7** [comment]
Thank you for letting us know. It's now fixed.
